clc; clear;
code_rate = 3/4;
N = 64800;
%generating H of frame length '64800 bits'
H = dvbs2ldpc(3/4); 

no_columns_H = N;
k = N*code_rate; % no. of info bits
no_rows_H = no_columns_H - k;
u = randi([0 1], k, 1);
% Saving input vector generated by randi() to a text to use it as input in
% testing Alogrithm
writematrix(u, 'E:\LDPC_Encoder\info_bits.txt');

cfg = ldpcEncoderConfig(H);
codeword = ldpcEncode(u, cfg);

disp(codeword.');




















